name: Build ExPiliplus for Mac

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag, e.g. v1.0.0 or v1.0.0-dev.1"
        required: false
        default: ""
        type: string

jobs:
  build-mac-app:
    name: Release Mac
    runs-on: macos-26
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1 -Platform macos -Tag "${{ inputs.tag }}"

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 macOS

      - name: Build Mac
        run: >-
          flutter build macos --release
          --build-name="${{ env.native_version }}"
          --build-number="${{ env.version_code }}"
          --dart-define-from-file=pili_release.json

      - name: Prepare Upload
        run: |
          npm install --global create-dmg
          create-dmg build/macos/Build/Products/Release/ExPiliplus.app || true
        continue-on-error: true

      - name: Rename DMG
        run: mv ExPiliplus*.dmg ExPiliplus_macos_${{ env.version }}.dmg

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          prerelease: ${{ fromJSON(env.is_prerelease) }}
          make_latest: ${{ env.is_prerelease == 'true' && 'false' || 'true' }}
          files: |
            ExPiliplus_macos_*.dmg

      - name: Upload macos release
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: ExPiliplus_macOS_release
          path: ExPiliplus_macos_*.dmg
